Dungeon
zwarag/dungeon-crawler pull request #4
Opened 2021-10-08 11:18 UTC by Henchway

2021-10-08 13:01 UTC, zwarag requested changes

2021-10-08 13:01 UTC, zwarag commented on app/src/helper/grid-elements.ts
> +}
![image](https://user-images.githubusercontent.com/2607973/136561560-a9db8bfc-7130-4e71-9135-58ad92046900.png)

2021-10-08 13:52 UTC, Chrono666 commented on app/src/game.ts
> +        const wallMaterial = new THREE.MeshBasicMaterial({map: wallTexture}) // img source: https://www.pinterest.at/pin/376402481328234967/
hab das wall.jpg getauscht, über die Art/Farbe der Ziegel können wir noch reden. Aber am besten wir nehmen eine Texture von hier https://polyhaven.com/textures. Diese dann zu ändern und ein neues Bild zu erstellen dauert dann nur 5~10 min.

2021-10-09 16:05 UTC, zwarag commented on yarn-error.log
> +Arguments:
we propably won't need this :)

2021-10-09 16:06 UTC, zwarag commented on app/src/character.ts
> +                    if (this.checkFreeSpace(newPosition, this.Element.position.z, scene)) {
Ich kann jetzt z.b nicht auf den gelben cone drauf.

2021-10-09 16:08 UTC, zwarag commented on app/src/character.ts
> +        const intersections = scene.children.filter(value =>
nice use of filter

2021-10-09 16:09 UTC, zwarag commented on app/src/character.ts
> +    moveCharacter(scene: Scene): void {
Für späteres improvement vl eine überlegung wert nur die referenz zu einer liste von objekten die gezeichnet werden, statt der gesamten Scene.

2021-10-09 16:11 UTC, zwarag commented on app/src/game.ts
> +        this._dungeon = new Dungeon()
nice idee das auszulagern, dann können wir das bei einem level wechsel wiederverwenden.

2021-10-09 16:12 UTC, zwarag commented on app/src/helper/random.ts
> +export function randomRange(start:number, stop:number) : number{
🔥💯

2021-10-09 16:13 UTC, zwarag commented on package-lock.json
> +{
dieses file bitte wieder löschen und yarn zum verwalten der packages verwenden

2021-10-10 10:48 UTC, Henchway commented on app/src/character.ts
> +            value.position.z == z && value.position.x == x
Isn't it wurscht? :D

2021-10-10 10:49 UTC, Henchway commented on app/src/character.ts
> +    moveCharacter(scene: Scene): void {
Yep, könnte man auch schon direkt runterbrechen auf die positions der Objekte.

2021-10-12 16:59 UTC, closed without merging